# my config
version: 2.1
orbs:
  node: circleci/node@3.0.1
  docker: circleci/docker@1.4.0
jobs:
  build-and-push:
    environment: 
      DOCKER_IMAGE: ddnn2026/react-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  my-pipeline:
    jobs:
      - node/test
      - build-and-push:
          filters:
            branches:
              only:
                - master